# Generated by Django 4.2.15 on 2024-09-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribution', '0008_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='receipt_number',
            new_name='receipt',
        ),
        migrations.AlterField(
            model_name='premium',
            name='pay_type',
            field=models.CharField(db_column='PayType', default='Cash', max_length=1),
        ),
    ]
